export const ZONES = [
  { key: "meadow", label: "Meadow Trailhead", icon: "🌱", tint: "111,169,138", center: 0.06 },
  { key: "woods", label: "Whispering Woods", icon: "🌲", tint: "111,169,138", center: 0.28 },
  { key: "dunes", label: "Amber Dunes", icon: "🏜️", tint: "201,123,90", center: 0.5 },
  { key: "frost", label: "Frostpeak Ridge", icon: "❄️", tint: "143,182,201", center: 0.72 },
  { key: "hollow", label: "The Starfall Hollow", icon: "✨", tint: "155,135,196", center: 0.94 },
];

export const NODES: any[] = [
  { today: true, x: 50, zone: "meadow", mood: "+", title: "Today", date: "Not written yet", excerpt: "Your next waypoint is waiting." },
  { x: 28, zone: "meadow", mood: "🥾", title: "The Long Hike", date: "Jul 10, 2026", excerpt: "My legs ache, but the view from the ridge made every step worth it.", body: "My legs ache, but the view from the ridge made every step worth it. We started before sunrise and the trail was quiet except for our boots on gravel. Somewhere around the third mile I stopped thinking about the climb and just started noticing things — moss on the north side of the rocks, the way the wind changed above the treeline. Worth every ache." },
  { x: 70, zone: "meadow", mood: "☕", title: "Coffee with an Old Friend", date: "Jul 8, 2026", excerpt: "Three hours passed like ten minutes — some conversations don't age.", body: "Three hours passed like ten minutes — some conversations don't age. We picked up exactly where we left off two years ago, like no time had passed at all. Funny how the best friendships work that way. Left the café with my coffee cold and untouched, and I didn't mind at all." },
  { x: 24, zone: "woods", mood: "💻", title: "Deadline Crunch", date: "Jul 6, 2026", excerpt: "Shipped it at 11:58pm. Tired, but proud of what we built.", body: "Shipped it at 11:58pm. Tired, but proud of what we built. The last two hours were pure adrenaline — three of us on a call, fixing things in real time. When the deploy finally went green, nobody said anything for a second. Then everyone just started laughing." },
  { x: 68, zone: "woods", mood: "🎆", title: "Fireworks & Reflection", date: "Jul 4, 2026", excerpt: "Watched the sky light up and thought about how far this year has taken me.", body: "Watched the sky light up and thought about how far this year has taken me. Sat on the roof with a blanket and let my mind wander through the last six months — the moves, the mistakes, the small wins nobody saw. Grateful, mostly." },
  { x: 30, zone: "dunes", mood: "🌱", title: "New Month, New Habit", date: "Jul 1, 2026", excerpt: "Day one of morning runs. Ask me again in thirty days.", body: "Day one of morning runs. Ask me again in thirty days. Woke up before the alarm out of pure nervous energy. Only made it two miles but my knees are already filing a complaint. Small start, but a start." },
  { x: 72, zone: "dunes", mood: "🌧️", title: "Rainy Day Thoughts", date: "Jun 27, 2026", excerpt: "Stayed in, made soup, let my mind wander somewhere quiet.", body: "Stayed in, made soup, let my mind wander somewhere quiet. There is a particular kind of peace in a rainy afternoon with nowhere to be. Read half a book. Answered no emails. Ten out of ten, would rain again." },
  { x: 26, zone: "frost", mood: "🏆", title: "A Small Victory", date: "Jun 22, 2026", excerpt: "Finally fixed the bug that haunted me all week. Small wins count.", body: "Finally fixed the bug that haunted me all week. Small wins count. It was a single misplaced condition, of course it was. Felt the specific joy of a problem clicking into place after days of nothing." },
  { x: 66, zone: "frost", mood: "🏠", title: "Missing Home", date: "Jun 15, 2026", excerpt: "Called Mom for two hours. Some distances only a voice can close.", body: "Called Mom for two hours. Some distances only a voice can close. We talked about nothing in particular — the garden, the neighbors, a recipe I keep meaning to try. Hung up lighter than I felt all week." },
  { x: 32, zone: "hollow", mood: "😅", title: "First Week Nerves", date: "Jun 8, 2026", excerpt: "New city, new job, new everything. Trying to breathe through the unknown.", body: "New city, new job, new everything. Trying to breathe through the unknown. Got lost twice on the way to a meeting I was already nervous about. Nobody seemed to notice. Maybe that is the secret — nobody is watching as closely as you think." },
  { x: 50, zone: "hollow", mood: "✨", title: "Where It All Began", date: "Jun 1, 2026", excerpt: "Opened this journal for the first time. Let's see where it leads.", body: "Opened this journal for the first time. Let's see where it leads. No real plan, just a page and an urge to remember things properly for once. Here's to whoever I am by the time this trail runs out." },
];
